resources:
- name: test-app
  type: git
  source:
    uri: https://github.com/piskandar/test-app.git
    branch: master

jobs:
  - name: test
    plan:
      - get: test-app
      - task: test
        file: test-app/concourse/tasks/test/test.yml
  - name: build
    plan:
      - get: test-app
        trigger: true
        passed: [test]
      - task: build
        file: test-app/concourse/tasks/build/build.yml
  - name: clean
      plan:
        - get: test-app
          trigger: true
          passed: [build]
        - task: clean
          file: test-app/concourse/tasks/clean/clean.yml